const mongoose = require("mongoose");
const Schema = mongoose.Schema;
const ObjectId = Schema.ObjectId;

const courseSchema = new Schema({
  id: ObjectId,
  lectures: [{
    id: ObjectId,
    date: {
      type: Date,
    },
    autoGeneratedCode: {
        type: Number,
    },
    attendance: [{
            type: String,
            required: [true, "Please provide usernames"]
    }]
  }],
  courseName: {
    type: String,
    required: [true, "Please provide course name"]
  },
  studentAmount:{
    type: Number,
    required: true
  },
  teacherName: {
    type: String,
    required: [true, "Please provide a teacher name"]
  },
  
});

const Course = mongoose.model("Course", courseSchema);

module.exports = Course;
